### ISSUE TITLE
Cant update kali from 2020.3 to 2020.4
Pls help🙏

### ISSUE THREAD

**Issue by rishabh-shamaa** [baljeet-singh97/KaliLinux2020.4#1]
![Uploading IMG_20210203_223537.jpg …]()

**Comment by baljeet-singh97** [comment]
| Use these commands in your kali terminal |

echo "deb http://http.kali.org/kali​ kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list

sudo apt update && sudo apt -y full-upgrade

cp -i /etc/skel/.bashrc ~/

cp -i /etc/skel/.zshrc ~/

chsh -s /bin/zsh

[ -f /var/run/reboot-required ] && sudo reboot -f
